<?php
//Main
$language_basic = array(
	'A'						=>	'个',
	'Please'				=>	'请',
	'Year'					=>	'年',
	'Day'					=>	'天',
	'Hour'					=>	'小时',
	'Minute'				=>	'分钟',
	'Jooyea'				=>	'聚易',
	'Friend'				=>	'好友',		
	'Online'				=>	'在线',
	'Busy'					=>	'忙碌',
	'Leave'					=>	'离开',
	'Hiding'				=>	'隐身',
	'Offline'				=>	'离线',
	'Manage'				=>	'管理',
	'Setting'				=>	'设置',
	'Confirm'				=>	'确定',
	'Successfully'			=>	'成功！',
	'Failed'				=>	'失败！',
	'Out'					=>	'退出',
	'Close'					=>	'关闭',
	'Cancel'				=>	'取消',
	'Delete'				=>	'删除',	
	'Modify'				=>	'修改',	
	'Select'				=>	'选择',
	'Msg'					=>	'消息',
	'Ellipsis'				=>	'...',
	'Move'					=>	'移动>>',
	'Min'					=>	'最小化',
	'Stranger'				=>	'陌生人',
	'DiscussionGroup'		=>	'讨论组',
	'OnlineFriend'			=>	'在线好友',
	'SearchFriend'			=>	'搜索好友',
	'userico'				=>	'用户头像',
	'CloseContacted'		=>	'最近联系人',
	'SysSetting'			=>	'系统设置',
	'BasicSetting'			=>	'基本设置',
	'Anticlutter'			=>	'安全隐私',
	'updateMood'			=>	'编辑心情',
	'FriendsList'			=>	'好友列表',
	'UploadUserIco'			=>	'上传头像',
	'ClickForDownload'		=>	'点击下载',
	'OnlineTime'			=>	'在线时间：',
	'MyFriend'				=>	'我的好友',	
	'AvatarSetting'			=>	'头像设置',
	'YouHaveNewMsg'			=>	'您有新消息',
	'FileIsNotExist'		=>	'文件不存在！',
	'SelectUploadFile'		=>	'选择上传文件',
	'PlayAudio'				=>	'开启声音提示',	
	'InputName'				=>	'请输入好友姓名',
	'LanguageChange'		=>	'切换到繁体中文',
	'CannotFindFriend'		=>	'没有找到匹配的好友',
);

//在线状态
$language_online = array(
	'0'						=>	'在线',
	'1'						=>	'在线',
	'2'						=>	'隐身',
	'3'						=>	'忙碌',
	'4'						=>	'离开',
);

//好友
$language_friend = array(
	'DelGroupWarning'		=>	"选定的分组将被删除，组内的好友将被移动到系统默认分组“我的好友”。\r\n您确定要删除该分组吗？",	
	'DelFriendWarning'		=>	"删除好友将一并删除与此好友的聊天记录！\r\n确认删除？",
	'InputGroupName'		=>	'请输入分组名称！',
	'AddNewGroup'			=>	'创建新分组',
	'Group'					=>	'分组',
	'SearchUser'			=>	'查找联系人',
	'Search'				=>	'查 找',	
);

//聊天窗口
$language_talkwin = array(
	'Invite'				=>	'邀请',
	'Report'				=>	'举报',
	'ClearWindow'			=>	'清屏',
	'SearchFace'			=>	'选择表情',
	'FileTransfer'			=>	'文件传输',
	'Send'					=>	'发送',
	'LastWord'				=>	'剩余字数：',
	'Record'				=>	'聊天记录',
	'PreviousPage'			=>	'上一页',
	'NextPage'				=>	'下一页',
	'NowPage'				=>	'第',
	'Page'					=>	'页',
	'PageSum'				=>	'总共',
	'PleaseSelect'			=>	'请选择',
	'NowPageSelect'			=>	'当前页',
	'Whole'					=>	'全部',
	'Annal'					=>	'记录',
	'DeleteThisRecord'		=>	'删除本条记录',
	'ConfirmDel'			=>	'确定删除？',
	'BecomeFriend'			=>	'加为好友',
	'NowTransferFile'		=>	'正在传送文件: ',	
	'AddFriendSuccessfully'	=>	'已成功加为好友',
	'AddFriendFailed'		=>	'加为好友失败',
	'RefuseToBeFriend'		=>	'对方拒绝任何人加为好友！',
	'HasBeenInFriendList'	=>	'已在您的好友列表里',
	'WrongAnswer'			=>	'答案错误！',
	'NeedToAnswerQuestion'	=>	'对方需要您回答一下验证问题：',
	'InputTheAnswer'		=>	'请输入问题答案！',
	'SystemNotice'			=>	'【系统提示】',
	'Loading'				=>	'正在加载请稍候。。。',
	'NoChattingRecord'		=>	'无聊天记录！',
	'Video'					=>	'视频',
	'TransferImg'			=>	'发送图片',
	'MessageRecord'			=>	'消息记录',
	'GooupInfo'				=>	'群信息',
	'TalkGroupMember'		=>	'讨论组成员',
	'VideoIsCanceled'		=>	'视频请求已取消！',
	'VideoContacted'		=>	'视频连接成功！',
	'PostEnter'				=>	'按Enter键发送消息',
	'PostCtrlEnter'			=>	'按Ctrl+Enter键发送消息',
	'PostAltS'				=>	'按Alt+S键发送消息',
);

//讨论组
$language_group = array(
	'CreateGroup'			=>	'创建组',
	'CreateTalkGroup'		=>	'创建讨论组',
	'SearchGroup'			=>	'查找组',
	'SearchTalkGroup'		=>	'查找讨论组',
	'MyGroup'				=>	'我创建的讨论组',
	'MyOtherGroup'			=>	'我加入的讨论组',
	'GroupName'				=>	'讨论组名称：',
	'InsertGroupName'		=>	'请输入您要创建的讨论组的名称',
	'GroupWarn'				=>	'<p><b>创建讨论组注意事项：</b></p><p>一个讨论组最多人数限制30人。</p><p>创建成功后的讨论组可以通过讨论组管理进行管理。</p><p>请不要创建重复的讨论组。</p>',
	'GroupIsFull'			=>	'[讨论组满员]',
	'NoMyGroup'				=>	'没有我创建的讨论组！',
	'NoMyOtherGroup'		=>	'没有我所加入的讨论组！',
	'Dismiss'				=>	'解散',
	'Manage'				=>	'管理',
	'Out'					=>	'退出',
	'Application'			=>	'申请',
	'Already'				=>	'已经',
	'JoinIn'				=>	'加入',
	'People'				=>	'人',
	'MemberManage'			=>	'成员管理',
	'MemberRestraint'		=>	'添加成员不能超过30人',
	'MemberEditSuccessfully'=>	'讨论组成员编辑成功！',
	'OutGroupSuccessfully'	=>	'您已成功退出讨论组！',
	'ReenterGroupName'		=>	'请重新输入要查找的讨论组！',
	'NotFoundGroup'			=>	'没有找到相关的讨论组！',
);

//安全隐私
$language_limit = array(
	'AllowAnyBody'			=>	'允许任何人加我为好友',
	'NeedQuestion'			=>	'需要回答问题',
	'Question'				=>	'问题',
	'Answer'				=>	'答案',
	'RefuseAnyBody'			=>	'禁止任何人加我为好友'
);

//表情
$language_face = array(
	'Smile'					=>	'微笑',
	'Grin'					=>	'呲牙笑',
	'Titter'				=>	'偷笑',
	'OutTongue'				=>	'吐舌',
	'BadSmile'				=>	'色迷迷',
	'Ashamed'				=>	'害羞',
	'Cool'					=>	'耍酷',
	'Dizzy'					=>	'晕',
	'Doubt'					=>	'疑惑',
	'Sweat'					=>	'流汗',
	'Sad'					=>	'难过',
	'Dissatisfied'			=>	'不满',
	'Amazed'				=>	'吃惊',
	'NotUnderstand'			=>	'不明白',
	'Angry'					=>	'生气',
	'Anger'					=>	'暴怒',
	'Sleeping'				=>	'睡觉',
	'ShutUp'				=>	'闭嘴',
	'Weak'					=>	'衰',
	'Pig'					=>	'猪头',
	'Heart'					=>	'红心',
	'HeartCold'				=>	'心碎',
	'Flower'				=>	'鲜花',
	'Wither'				=>	'凋谢',
	'Goodnight'				=>	'晚安',
	'Knock'					=>	'拍砖',
	'Money'					=>	'金钱',
	'Feces'					=>	'便便',
	'Vomit'					=>	'呕吐',
	'Baste'					=>	'扁你',
	'Good'					=>	'好',
	'Applause'				=>	'鼓掌',
	'Support'				=>	'支持你',
	'Despise'				=>	'鄙视你',
	'Surrender'				=>	'投降',
	'Winner'				=>	'胜利',
	'OK'					=>	'OK',
	'Handshake'				=>	'握手',
	'Hug'					=>	'抱抱',
	'Pump'					=>	'抽你',
	'Kiss'					=>	'亲一个',
	'Grievance'				=>	'委屈',
	'Wail'					=>	'痛哭',
	'Exclaim'				=>	'惊叫',
	'Mad'					=>	'抓狂',
	'Thurification'			=>	'烧香',
	'Expectation'			=>	'期望',
	'Talk'					=>	'喊话',
	'Invigorating'			=>	'爽歪歪',
);

//文件传输
$language_transfer = array(
	'FileNotExist'			=>	'文件不存在',
	'OutRestraint'			=>	'文件大小超过了服务器限制',
	'TransferFailed'		=>	'文件传输失败！',
	'UnknowType'			=>	'文件类型不符合，允许上传的文件类型是：',
	'PermitFileType'		=>	'服务器不允许传输此类文件！',
	'FileUpdateToServer'	=>	'文件已成功上传至服务器',	
	'TransferFileOff'		=>	'服务器暂不支持文件传输',	
);